#!/usr/bin/env python3

# Inspired by: https://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu

import io
import glob
import os.path
import subprocess

prefix = os.path.expanduser('~/.password-store/')
password_files = {
    path[len(prefix):-len('.gpg')]
    for path in
    glob.glob(f'{prefix}**/*.gpg')
}

p = subprocess.Popen(
    'fzf',
    stdin=subprocess.PIPE,
    stdout=subprocess.PIPE,
    text=True,
)
stdout, _ = p.communicate(input='\n'.join(password_files))

password = stdout.strip()

subprocess.run(
    ['pass', '-c', password],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)

